### ISSUE TITLE
bitexen-client yükleme problemi

### ISSUE THREAD

**Issue by buraktuzun** [Bitexen/bitexen-python#2]
Client yüklerken hata alıyorum.

`Collecting bitexen-client
  Using cached bitexen_client-0.0.15.tar.gz (4.6 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\python27\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'c:\\users\\username\\appdata\\local\\temp\\pip-install-ubhf4r\\bitexen-client\\setup.py'"'"'; __file__='"'"'c:\\users\\username\\appdata\\local\\temp\\pip-install-ubhf4r\\bitexen-client\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'c:\users\username\appdata\local\temp\pip-pip-egg-info-xwdnnz'`

**Comment by kosehakan** [comment]
Python 3.8.3 sürümünü yükleyin. AddPath seçeneği seçili olmasına özen gösterin. pip sürümünü güncelleyin.

**Comment by mehmetboraezer** [comment]
Sorunu çözebildiniz mi? @buraktuzun

**Comment by kosehakan** [comment]
> Sorunu çözebildiniz mi? @buraktuzun

Anlattığım yöntem ile python da çalışmama sorununu aşmış oldum. Diğer önemli konu örnekte yeralan linklerin değiştirilmesi gerekiyor. Çalışan koddan bir örnek olarak ekliyorum.

def order_book():
    api = API(uri='https://www.bitexen.com/')
    results = api.get_order_book('BTCTRY')
    print(results)
    return results


def ticker():
    api = API(uri='https://www.bitexen.com/')
    results = api.get_ticker('BTCTRY')
    #print(results)
    return results

kolaylıklar dilerim.

**Comment by mehmetboraezer** [comment]
@kosehakan Sorunun çözülmesine sevindim. Örnek URL'lerin değiştirilmesi konusunda da bahsettiğiniz değişikliği yapmıştık. Şuradaki committen görebilirsiniz; 3b5e331c3e577e366994a619c556f708e290ce6e.

Sorun çözüldüğü için issue'yu kapatıyorum. 👍  ✋

**Comment by buraktuzun** [comment]
Henüz deneyemedim. Bu sıralar biraz yoğunum. Desteğiniz için teşekkürler.

6 Tem 2020 Pzt 15:07 tarihinde Mehmet Bora Ezer <notifications@github.com>
şunu yazdı:
