### ISSUE TITLE
Adreslerin değiştirilmesi lazım

### ISSUE THREAD

**Issue by metin02oktay** [Bitexen/bitexen-python#3]
https://github.com/Bitexen/bitexen-python/blob/c4e6be9e6ee631ed5958d7451a6959f60b8f2432/examples/example.py#L11

Adresler hatalı değişmesi gerek. İlgilenen yok galiba(Tıpkı müşteri hizmetlerine atılan epostalar gibi, geridönüşü olmuyor....).

**Comment by mehmetboraezer** [comment]
Merhaba, belirtmiş olduğunuz sorun düzeltildi (https://github.com/Bitexen/bitexen-python/commit/3b5e331c3e577e366994a619c556f708e290ce6e).
